import type { Metadata } from 'next';
import { Contact } from "../../src/components/contact";
import React from "react";

export const metadata: Metadata = {
  title: 'Contact Us - Plan Your African Safari Adventure | Dawnlight Journeys',
  description: 'Ready to start your African adventure? Contact Dawnlight Journeys today to plan your perfect safari experience in Uganda and Rwanda. Expert travel consultants available 24/7.',
  keywords: [
    'contact dawnlight journeys',
    'safari booking',
    'african safari planning',
    'uganda safari booking',
    'rwanda safari booking',
    'gorilla trekking booking',
    'wildlife safari booking',
    'custom safari planning',
    'safari consultation',
    'travel planning africa',
    'safari expert contact',
    'african adventure planning',
    'safari package booking',
    'luxury safari booking',
    'family safari planning',
    'honeymoon safari booking',
    'group safari booking',
    'private safari planning',
    'safari itinerary planning',
    'african wildlife tour booking',
    'cultural tour booking',
    'photography safari booking',
    'bird watching tour booking',
    'conservation safari booking',
    'eco-tourism booking',
    'sustainable safari booking',
    'local guide booking',
    'safari guide contact',
    'african travel expert',
    'safari travel consultant',
    'african adventure consultant',
    'safari package deals',
    'safari vacation planning',
    'african holiday booking',
    'safari trip planning',
    'african wildlife experience',
    'gorilla trekking expert',
    'chimpanzee tracking booking',
    'big five safari booking',
    'african safari operator',
    'safari company contact',
    'safari agency contact',
    'dawnlight journeys contact',
    'rwanda safari operator',
    'uganda safari operator',
    'east african safari booking',
    'african safari expert',
    'safari travel agency',
    'african adventure agency',
    'wildlife tour operator',
    'nature tour booking',
    'cultural experience booking',
    'authentic african experience',
    'local community tour',
    'traditional village visit',
    'african heritage tour',
    'indigenous culture tour',
    'tribal experience booking',
    'african tradition tour',
    'cultural immersion booking',
    'authentic safari experience',
    'local guide booking',
    'community tourism booking',
  ],
  openGraph: {
    title: 'Contact Us - Plan Your African Safari Adventure | Dawnlight Journeys',
    description: 'Ready to start your African adventure? Contact Dawnlight Journeys today to plan your perfect safari experience in Uganda and Rwanda. Expert travel consultants available 24/7.',
    url: 'https://dawnlightjourneysrwanda.com/contact',
    siteName: 'Dawnlight Journeys',
    images: [
      {
        url: 'https://res.cloudinary.com/nishimweprince/image/upload/f_auto,q_auto/v1/dawnlight-journeys/contact-safari_planning',
        width: 1200,
        height: 630,
        alt: 'Contact Dawnlight Journeys for Safari Planning',
      },
      {
        url: 'https://res.cloudinary.com/nishimweprince/image/upload/f_auto,q_auto/v1/dawnlight-journeys/safari-consultation_expert',
        width: 1200,
        height: 630,
        alt: 'Safari Consultation with Expert Guides',
      },
      {
        url: 'https://res.cloudinary.com/nishimweprince/image/upload/f_auto,q_auto/v1/dawnlight-journeys/african-adventure_planning',
        width: 1200,
        height: 630,
        alt: 'African Adventure Planning',
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Contact Us - Plan Your African Safari Adventure | Dawnlight Journeys',
    description: 'Ready to start your African adventure? Contact Dawnlight Journeys today to plan your perfect safari experience in Uganda and Rwanda. Expert travel consultants available 24/7.',
    site: '@dawnlightjourneys',
    creator: '@pnishimwe',
    images: [
      'https://res.cloudinary.com/nishimweprince/image/upload/f_auto,q_auto/v1/dawnlight-journeys/contact-safari_planning',
      'https://res.cloudinary.com/nishimweprince/image/upload/f_auto,q_auto/v1/dawnlight-journeys/safari-consultation_expert',
      'https://res.cloudinary.com/nishimweprince/image/upload/f_auto,q_auto/v1/dawnlight-journeys/african-adventure_planning',
    ],
  },
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: false,
      'max-snippet': -1,
      'max-image-preview': 'large',
      'max-video-preview': -1,
    },
  },
  alternates: {
    canonical: 'https://dawnlightjourneysrwanda.com/contact',
  },
};

export default function ContactPage() {
  return <Contact />;
} 